server:
  servlet:
    session:
      timeout: 60m

  compression:
    enabled: true

  port: ${LOCAL_SERVER_PORT}

  tomcat:
    threads:
      max: 500
      min-spare: 50
    max-connections: 10000
    accept-count: 1000
    max-http-form-post-size: 100MB

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  config:
    activate:
      on-profile: local
    include: env

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    redis:
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5
          max-wait: 1000
      port: ${LOCAL_REDIS_PORT}
      host: ${LOCAL_REDIS_HOST}
      connect-timeout: 100000
      timeout: 180000

springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.core

logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/freeblog_util.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

tus_util:
  upload_directory: ${LOCAL_TUS_UPLOAD_DIRECTORY}
  expiration: ${LOCAL_TUS_EXPIRATION}
  upload_url: ${LOCAL_TUS_UPLOAD_URL}
  video_token_recreate: ${LOCAL_VIDEO_TOKEN_RECREATE}